#! /bin/bash
# Author: David Curie
# Description: Rename files and move them to a new directory.
# Result:
#   - Convert dates in filename from MMDDYY to YYYY-MM-DD
#   - Move files with high-temp in name to high-temp folder
#   - Move non-labeled data to room-temp folder and append room-temp label
#   - Find any files with above-normal spectra and list them in to-clean.txt

rename_dates () {
    for file in *.txt;
    do
        mv $file $(echo $file | sed -E 's/([0-9]{2})([0-9]{2})([0-9]{2})/20\3-\1-\2/')
    done
}


move_to_room_temp () {
    # Call this after moving all other high-temp files and creating room-temp/
    mv $1 $(echo $1 | sed -E 's/(.*).txt/room-temp\/\1_room-temp.txt/')
}

find_outliers_from_files () {
    # Assuming 'counts' data above 356 is an outlier
    files_to_search=$@
    grep -E -l '\t35[6-9]|\t3[6-9][0-9]*|\t[4-9][0-9]*' ${files_to_search} >> to-clean.txt
    awk '!seen[$0]++' to-clean.txt > sorted-clean.txt
    mv sorted-clean.txt to-clean.txt

}

rename_dates

mkdir -p high-temp
for file in *high-temp*;
do
    mv $file high-temp/
done

mkdir -p room-temp
for file in *.txt;
do
    move_to_room_temp $file
done

find_outliers_from_files */*results*
